package com.example.chatbotwhatsapp.enums;

public enum ChatState {
    START,
    SHOW_PERSONAL_INFO,
    OPPORTUNITIES,
    PROJECTS,
    SHOW_OPPORTUNITIES,
    PROJECTS_COMMERCIAL_OU_CHEF,
    SHOW_PROJECTS,
    SHOW_PROJECTS_COMMERCIAL,
    SHOW_PROJECTS_CHEFPROJET,
    NO_OPPORTUNITIES,
    NO_PROJECTS,
    SAISIR_STATUS_OPPORTUNITE,
    SAISIR_STATUS_PROJET,
    SAISIR_NOM_OPPORTUNITE,
    SAISIR_NOM_PROJET,
    SHOW_PROJECTS_BY_STATUS,
    SHOW_OPPORTUNITIES_BY_STATUS,
    NO_OPPORTUNITIES_BY_STATUS,
    NO_PROJECTS_BY_STATUS,
    SHOW_OPPORTUNITIES_NAME_DETAILS,
    SHOW_PROJECTS_NAME_DETAILS,
    NO_OPPORTUNITIES_NAME_DETAILS,
    NO_PROJECTS_NAME_DETAILS,
    UNKNOWN_RESPONSE

}
